# Generated by Django 4.0.2 on 2022-02-01 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_bids', '0002_alter_category_options_auction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10, message='Please enter at least 10 characters.')]),
        ),
    ]
