# Generated by Django 4.0.2 on 2022-02-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_bids', '0006_alter_comment_auction_alter_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='user',
            new_name='user_id',
        ),
    ]
